AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: sshysh-key-pair
  AmiId:
    Description: The ID of the AMI to use for the EC2 instance(Def - Ubuntu Server 20.04 LTS 64-bit x86)
    Default: ami-0ca5c3bd5a268e7db
    Type: String
  InstanceType:
    Description: The type of the EC2 instance
    Default: t2.micro
    Type: String
    AllowedValues:
      - t2.micro
Resources:
  testLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: testLaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroups:
          - !Ref SshSecurityGroup
          - !Ref HttpSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            add-apt-repository -y ppa:openjdk-r/ppa
            apt-get update -y
            apt-get install -y openjdk-8-jre-headless
  testASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: testASG
      MinSize: '2'
      MaxSize: '3'
      DesiredCapacity: '2'
      LaunchTemplate:
        LaunchTemplateId: !Ref testLaunchTemplate
        Version: !GetAtt testLaunchTemplate.LatestVersionNumber
      AvailabilityZones:
        - us-west-2a
      HealthCheckGracePeriod: 90
  SshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  HttpSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http/https to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
